version: '2'

services:
 
    backup:
        image: loomchild/volume-backup:latest
        volumes: 
            - volume:/volume
            - backup:/backup
        command: ["backup", "${ARCHIVE}"]

    restore:
        image: loomchild/volume-backup:latest
        volumes: 
            - volume:/volume
            - backup:/backup
        command: ["restore", "${ARCHIVE}"]

    list:
        image: alpine
        volumes: 
            - backup:/backup
        command: ["sh", "-c", "sleep 0.1; ls -1 --color=never /backup/${ARCHIVE}"]

volumes:
    volume:
        external:
            name: ${VOLUME}
    backup:
        external:
            name: ${BACKUP}

